name: setup-node
description: 'Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4
    - name: Use Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: 'pnpm'

    - name: Cache dependencies ⚡
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install dependencies 🔧
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
